export default {
  introduction: 'Introduction',
  account_master: 'Account Master',
  bank_master: 'Bank Master',
  bank_import: 'Bank Import',
  fee_receipt: 'Fee Receipt',
  receipt_report: 'Receipt Report',
  payment_window: 'Payment Window',
  dollar_inr: 'Dollar to INR Conversion Rate',
  collection_summary: 'Collection Summary',
  draft_voucher: 'Draft Voucher',
  payment_voucher_verification: 'Payment Voucher Verification',
  payment_voucher_approval: 'Payment Voucher Approval',
  draft_journal_voucher: 'Draft Journal Voucher',
  journal_voucher_verification: 'Journal Voucher Verification',
  voucher_master: 'Voucher Master',
  dd_details_report: 'DD Details Report',
  student_fee_refund: 'Student Fee Refund',
  paid_fee_update: 'Paid Fee Update',
};
