# ❌ Student Cancellation

The **Student Cancellation** section under the Approver tab is designed for authorized employees to view and manage student admission cancellation requests. These requests are generated by other employees within the Acharya system.

---

## 🎯 Purpose

This functionality allows authorized employees to:

- View all student admission cancellation requests initiated by other staff members.
- Review each request in a structured, tabular format.
- Approve the cancellation requests based on the provided information.

---

## 🔐 Access Rights

- Only employees with the appropriate authorization can access this tab and perform approval actions.

---

## 📊 Data Display

In the tabular view of the Student Cancellation section, the following details are shown for each cancellation request:

- **AUID**: Unique identification number assigned to the student.
- **Student Name**: Full name of the student whose admission is being cancelled.
- **School**: The school or department to which the student was admitted.
- **Remarks**: Any comments or notes provided related to the cancellation request.
- **Initiated By**: The name of the employee who initiated the cancellation request.
- **Initiated Date**: The date when the cancellation request was submitted.
- **Document**: Links or attachments related to the cancellation request (if any).
- **Application**: Details of the application related to the admission.
- **Approve**: An action button or option to approve the respective cancellation request.

---

This section ensures that all cancellation requests are processed transparently and in accordance with institutional policies.
