export default {
  'employee-master': 'Employee Master',
  'job-portal': 'Job Portal',
  'relieving-master': 'Relieving Master',
  'holiday-calendar': 'Holiday Calendar',
  'leave-history': 'Leave History',
  'initiate-leave': 'Initiate Leave',
  'research-report': 'Research Report',
  'employee-log': 'Employee Log',
  dashboard: 'Dashboard',
  'staff-data': 'Staff Data',
  'increment-initiation': 'Increment Initiation',
  'increment-repo': 'Increment Repository',
  'staff-attendance-inst': 'Staff Attendance Instructions',
  'staff_id-card': 'Staff ID Card',
  'vacation-leave-window': 'Vacation Leave Window',
};
